server:
  port: 8083

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - name: CircuitBreaker
          args:
            name: fallbackcmd
            fallbackUri: forward:/fallback

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

# 采样比率
management:
  tracing:
    sampling:
      probability: 1.0
# 将 traceId 和 spanId 和 log 绑定
logging:
  pattern:
    level: '%5p [${spring.application.name:test},%X{traceId:-},%X{spanId:-}]'
