server:
  port: 8087

spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shippingmanagement?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
  #  security:
  #    oauth2:
  #      resourceserver:
  #        jwt:
  #          issuer-uri: http://localhost:9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

# ????
management:
  tracing:
    sampling:
      probability: 1.0
# ? traceId ? spanId ? log ??
logging:
  pattern:
    level: '%5p [${spring.application.name:test},%X{traceId:-},%X{spanId:-}]'