server:
  port: 8086

spring:
  application:
    name: car-driver-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shippingmanagement?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
# 采样比率
management:
  tracing:
    sampling:
      probability: 1.0
# 将 traceId 和 spanId 和 log 绑定
logging:
  pattern:
    level: '%5p [${spring.application.name:test},%X{traceId:-},%X{spanId:-}]'

